# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi


# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"

ZSH_THEME="robbyrussell"

plugins=(
  git
)
  
source $ZSH/oh-my-zsh.sh

# antigen loaded
ANTIGEN_MUTEX=false
source /opt/homebrew/share/antigen/antigen.zsh
antigen init $HOME/.antigenrc


# initalize completions
# fpath=(/usr/local/share/zsh-completions $fpath)
if type brew &>/dev/null; then
 FPATH=$(brew --prefix)/share/zsh-completions:$FPATH

 autoload -Uz compinit
 compinit
fi


# loads nodenv
eval "$(nodenv init -)"
# initl python
eval "$(pyenv init --path)"

alias nrs='npm run start:watch:raw'
alias nd='npm run dev'
alias c='code ./'
alias gitclean="git branch | grep -v "master" | xargs git branch -D"
alias ls='colorls'
alias nv='nvim'

# The next line updates PATH for the Google Cloud SDK.
if [ -f '/Users/clarksell/google-cloud-sdk/path.zsh.inc' ]; then . '/Users/clarksell/google-cloud-sdk/path.zsh.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/Users/clarksell/google-cloud-sdk/completion.zsh.inc' ]; then . '/Users/clarksell/google-cloud-sdk/completion.zsh.inc'; fi

test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"
  
# bun completions
[ -s "/Users/csell/.bun/_bun" ] && source "/Users/csell/.bun/_bun"

# bun
export BUN_INSTALL="$HOME/.bun"
export PATH="$BUN_INSTALL/bin:$PATH"

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
