
# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"

ZSH_THEME="robbyrussell"

plugins=(
  git
)
  
source $ZSH/oh-my-zsh.sh

# antigen loaded
ANTIGEN_MUTEX=false
source /usr/local/share/antigen/antigen.zsh
antigen init $HOME/.antigenrc

# initalize completions
fpath=(/usr/local/share/zsh-completions $fpath)

# loads nodenv
eval "$(nodenv init -)"