
# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"

ZSH_THEME="robbyrussell"

plugins=(
  git
)
  
source $ZSH/oh-my-zsh.sh

# antigen loaded
ANTIGEN_MUTEX=false
source /usr/local/share/antigen/antigen.zsh
antigen init $HOME/.antigenrc

# initalize completions
fpath=(/usr/local/share/zsh-completions $fpath)

# loads nodenv
eval "$(nodenv init -)"

alias nrs='npm run start:watch:raw'
alias nd='npm run dev'
alias c='code ./'

# The next line updates PATH for the Google Cloud SDK.
if [ -f '/Users/clarksell/google-cloud-sdk/path.zsh.inc' ]; then . '/Users/clarksell/google-cloud-sdk/path.zsh.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/Users/clarksell/google-cloud-sdk/completion.zsh.inc' ]; then . '/Users/clarksell/google-cloud-sdk/completion.zsh.inc'; fi
